namespace: microsoft
name: ad
version: 1.4.1
readme: README.md
authors:
- Jordan Borean @jborean93
- Matt Davis @nitzmahone
description: |
  Ansible collection for Active Directory management
license_file: COPYING
tags:
- active_directory
- windows
dependencies: {}
repository: https://github.com/ansible-collections/microsoft.ad
documentation: https://docs.ansible.com/ansible/devel/collections/microsoft/ad
homepage: https://github.com/ansible-collections/microsoft.ad
issues: https://github.com/ansible-collections/microsoft.ad/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
- .vscode
- tests/integration/inventory*
- changelogs/.plugin-cache.yaml
