trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/microsoft/ad
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage-powershell
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:4.0.1

pool: Standard

stages:
  - stage: Dependencies
    displayName: Dependencies
    jobs:
    - job: dep_download
      displayName: Download Dependencies
      pool:
        vmImage: ubuntu-latest
      steps:
      - checkout: self
        fetchDepth: 1
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
      - bash: python -m pip install ansible-core
        displayName: Install Ansible
      - bash: ansible-galaxy collection install -r tests/requirements.yml -p collections
        displayName: Install collection requirements
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: collections
          artifactName: CollectionRequirements
  - stage: Ansible_devel
    displayName: Ansible devel
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: 'devel/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_15
    displayName: Ansible 2.15
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.15/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_14
    displayName: Ansible 2.14
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.14/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_13
    displayName: Ansible 2.13
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.13/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_12
    displayName: Ansible 2.12
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.12/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Windows
    displayName: Windows
    dependsOn:
    - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Server {0}
          testFormat: devel/windows/{0}
          targets:
            - test: 2016
            - test: 2019
            - test: 2022
          groups:
            - 1
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Ansible_devel
      - Ansible_2_15
      - Ansible_2_14
      - Ansible_2_13
      - Ansible_2_12
      - Windows
    jobs:
      - template: templates/coverage.yml
