trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/microsoft/ad
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage-powershell
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:6.0.0

pool: Standard

stages:
  - stage: Dependencies
    displayName: Dependencies
    jobs:
      - job: dep_download
        displayName: Download Dependencies
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            fetchDepth: 1
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.10"
          - bash: python -m pip install ansible-core
            displayName: Install Ansible
          - bash: ansible-galaxy collection install -r tests/requirements.yml -p collections
            displayName: Install collection requirements
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: collections
              artifactName: CollectionRequirements
  - stage: Ansible_devel
    displayName: Ansible devel
    dependsOn:
      - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: "{0}"
          testFormat: "devel/{0}"
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
            - name: Lint
              test: lint
  - stage: Ansible_2_17
    displayName: Ansible 2.17
    dependsOn:
      - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: "{0}"
          testFormat: "2.17/{0}"
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_16
    displayName: Ansible 2.16
    dependsOn:
      - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: "{0}"
          testFormat: "2.16/{0}"
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Ansible_2_15
    displayName: Ansible 2.15
    dependsOn:
      - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: "{0}"
          testFormat: "2.15/{0}"
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Windows
    displayName: Windows
    dependsOn:
      - Dependencies
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Server {0}
          testFormat: devel/windows/{0}
          targets:
            - name: Server 2016 WinRM HTTP
              test: 2016/winrm/http
            - name: Server 2019 WinRM HTTPS
              test: 2019/winrm/https
            - name: Server 2022 WinRM HTTPS
              test: 2022/winrm/https
            - name: Server 2022 PSRP HTTPS
              test: 2022/psrp/https
            - name: Server 2022 SSH Key
              test: 2022/ssh/key
          groups:
            - 1
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Ansible_devel
      - Ansible_2_17
      - Ansible_2_16
      - Ansible_2_15
      - Windows
    jobs:
      - template: templates/coverage.yml
